# Generated by Django 4.2.19 on 2025-04-17 01:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='exercice',
            name='fichier_pdf',
            field=models.FileField(blank=True, null=True, upload_to='exercices/', verbose_name='Fichier PDF'),
        ),
    ]
