# Generated by Django 4.2.19 on 2025-05-01 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='correction',
            name='plagiarism_report',
            field=models.JSONField(blank=True, null=True, verbose_name='Rapport de plagiat (similarités)'),
        ),
    ]
