# Generated by Django 4.2.19 on 2025-04-03 22:56

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exercice',
            name='modele_correction',
            field=models.FileField(blank=True, null=True, upload_to='modeles_correction/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'docx'])]),
        ),
    ]
