# Generated by Django 4.2.19 on 2025-05-01 20:00

from django.db import migrations

def fix_plagiarism_reports(apps, schema_editor):
    Correction = apps.get_model('gestion', 'Correction')
    Correction.objects.filter(plagiarism_report__isnull=True).update(plagiarism_report=[])

class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0002_correction_plagiarism_report'),
    ]

    operations = [
        migrations.RunPython(fix_plagiarism_reports),
    ]
