# Generated by Django 4.2.19 on 2025-04-23 19:47

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0002_exercice_coefficient'),
    ]

    operations = [
        migrations.AddField(
            model_name='classe',
            name='professeurs_supplementaires',
            field=models.ManyToManyField(blank=True, limit_choices_to={'role': 'PR'}, related_name='classes_enseignees_supplementaires', to=settings.AUTH_USER_MODEL, verbose_name='Professeurs supplémentaires'),
        ),
    ]
