# Generated by Django 4.2.19 on 2025-04-24 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0003_classe_professeurs_supplementaires'),
    ]

    operations = [
        migrations.AddField(
            model_name='exercice',
            name='difficulte',
            field=models.CharField(choices=[('Facile', 'Facile'), ('Moyenne', 'Moyenne'), ('Difficile', 'Difficile')], default='Moyenne', max_length=10, verbose_name='Niveau de difficulté'),
        ),
    ]
