# Generated by Django 4.2.19 on 2025-05-01 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0003_auto_20250501_2000'),
    ]

    operations = [
        migrations.AddField(
            model_name='correction',
            name='est_plagiat',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='correction',
            name='plagiarism_score',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='correction',
            name='plagiarism_report',
            field=models.JSONField(blank=True, default=list, help_text='Rapport de plagiat sous forme de liste', null=True),
        ),
    ]
