# Generated by Django 4.2.19 on 2025-04-04 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0004_alter_exercice_professeur'),
    ]

    operations = [
        migrations.AlterField(
            model_name='utilisateur',
            name='photo_profil',
            field=models.ImageField(blank=True, null=True, upload_to='profils/'),
        ),
    ]
