# Generated by Django 4.2.19 on 2025-04-04 23:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0005_alter_utilisateur_photo_profil'),
    ]

    operations = [
        migrations.AddField(
            model_name='soumission',
            name='score',
            field=models.FloatField(blank=True, null=True, verbose_name='Note obtenue'),
        ),
    ]
