# Generated by Django 4.2.19 on 2025-04-05 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('gestion', '0006_soumission_score'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='utilisateur',
            options={'verbose_name': 'user', 'verbose_name_plural': 'users'},
        ),
        migrations.RemoveField(
            model_name='soumission',
            name='score',
        ),
        migrations.RemoveField(
            model_name='utilisateur',
            name='username',
        ),
        migrations.AddField(
            model_name='utilisateur',
            name='fournisseur_oauth',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Fournisseur OAuth'),
        ),
        migrations.AddField(
            model_name='utilisateur',
            name='identifiant_oauth',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='ID OAuth'),
        ),
        migrations.AlterField(
            model_name='utilisateur',
            name='groups',
            field=models.ManyToManyField(blank=True, related_name='utilisateur_groups', related_query_name='utilisateur', to='auth.group', verbose_name='groups'),
        ),
        migrations.AlterField(
            model_name='utilisateur',
            name='role',
            field=models.CharField(choices=[('ET', 'Étudiant'), ('PR', 'Professeur')], default='etudiant', max_length=20),
        ),
    ]
