# Generated by Django 4.2.19 on 2025-04-05 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0007_alter_utilisateur_options_remove_soumission_score_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='utilisateur',
            name='matricule_temp',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
