# Generated by Django 4.2.19 on 2025-04-05 15:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0008_utilisateur_matricule_temp'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='utilisateur',
            name='matricule_temp',
        ),
    ]
