# Generated by Django 4.2.19 on 2025-04-08 23:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0010_exercice_date_inscription_alter_utilisateur_email_and_more'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='utilisateur',
            managers=[
            ],
        ),
        migrations.RemoveField(
            model_name='exercice',
            name='date_inscription',
        ),
        migrations.AddField(
            model_name='exercice',
            name='fichier_pdf',
            field=models.FileField(blank=True, null=True, upload_to='exercices/'),
        ),
    ]
