# Generated by Django 5.2 on 2025-04-08 21:37

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0010_exercice_date_inscription_alter_utilisateur_email_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='exercice',
            name='date_inscription',
        ),
        migrations.AddField(
            model_name='exercice',
            name='fichier_pdf',
            field=models.FileField(blank=True, null=True, upload_to='exercices/'),
        ),
        migrations.AddField(
            model_name='utilisateur',
            name='date_inscription',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='utilisateur',
            name='photo_profil',
            field=models.ImageField(blank=True, null=True, upload_to='profils/'),
        ),
    ]
