# Generated by Django 5.2 on 2025-04-08 23:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0011_remove_exercice_date_inscription_and_more'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='utilisateur',
            managers=[
            ],
        ),
    ]
