# Generated by Django 5.2 on 2025-04-14 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0012_alter_utilisateur_managers'),
    ]

    operations = [
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feedback_text', models.TextField(verbose_name='Feedback du professeur')),
                ('date_received', models.DateTimeField(auto_now_add=True, verbose_name='Date de réception')),
            ],
        ),
    ]
