# Generated by Django 5.2 on 2025-04-17 23:39

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0013_feedback'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='exercice',
            name='ponderation',
        ),
        migrations.AlterField(
            model_name='exercice',
            name='modele_correction',
            field=models.FileField(blank=True, null=True, upload_to='modeles_correction/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'docx'])], verbose_name='Modèle de correction'),
        ),
    ]
