# Generated by Django 5.2 on 2025-04-19 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0014_remove_exercice_ponderation_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='correction',
            name='contenu_brut',
            field=models.TextField(blank=True, null=True, verbose_name="Réponse brute de l'IA (non parsée)"),
        ),
    ]
